manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/scr47One/
  projects:
    - name: zmk
      remote: zmk-config-2
      revision: pr/1243
      import: app/west.yml
  self:
    path: config
