manifest:
  remotes:
    - name: scr47One
      url-base: https://github.com/scr47One
  projects:
    - name: zmk
      remote: scr47One
      revision: main
      import: app/west.yml
  self:
    path: config
